- core/src/main/kotlin/chat/rocket/core/internal/model/MessageResponse.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Logout.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LogoutTest.kt
> [NEW] Add rest call to logout implementation

- common/src/main/kotlin/chat/rocket/common/model/BaseMessage.kt
- core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
- core/src/main/kotlin/chat/rocket/core/model/Message.kt
Also set `Message` object `updatedAt` field nullable.
> Fix support to MessageAttachment

- core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LogoutTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
> [NEW] Rest API to upload file

- core/src/main/kotlin/chat/rocket/core/internal/rest/InputStreamRequestBody.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
Add an special RequestBody for use with Android, so we don't need an temporary file for uploads
> Add InputStreamRequestBody for use with Android.

- core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
> [NEW] Mark room as read

- core/src/main/kotlin/chat/rocket/core/internal/model/EmailLoginPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/model/LoginWithEmail.kt
- core/src/main/kotlin/chat/rocket/core/internal/model/UsernameLoginPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
Fixes #69 
Added classes - `EmailLoginPayload.kt`
Added functions - `RocketChatClient.loginWithEmail` inside `Login.kt`
A separate model class and function for supporting login with email have been added.
> [NEW] Support login with email

- core/src/main/kotlin/chat/rocket/core/internal/model/UserPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/SpotlightTest.kt
Sends the correct payload as per doc @ https://rocket.chat/docs/developer-guides/rest-api/users/update/
> Fix payload fields when updating user profile

- common/src/main/kotlin/chat/rocket/common/model/TimestampAdapter.kt
- core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/AudioAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/ImageAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/VideoAttachment.kt
> Fix TimestampAdapter and AttachmentAdapter

- common/build.gradle
- compat/build.gradle
- core/build.gradle
- core/src/main/kotlin/chat/rocket/core/internal/model/SocketMessage.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/Messages.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/Socket.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/UserPresence.kt
- dependencies.gradle
- rxjava/build.gradle
- sample/build.gradle
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
@RocketChat/android
Closes: #32 
Changes:
- Added UserStatus enum class
- Added setDefaultStatus(status) and setConnectionStatus(status) methods
- Updated dependencies (which was causing problem in running sample.kt)
> [NEW] feat: Add realtime-api method for UserStatus

- core/src/main/kotlin/chat/rocket/core/internal/model/SignUpPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
@RocketChat/android
Closes: #70
**Update Information**
- Added `SignUpPayload.kt`
- Changed `Login.kt` to account for changes
> [BUG] Fixed JSON Format for Profile Creation and Modification

- core/src/main/kotlin/chat/rocket/core/internal/model/CommandPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Commands.kt
- core/src/main/kotlin/chat/rocket/core/model/Command.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/CommandsConstants.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/CommandsTest.kt
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/87 should be merged first before this one.
> [NEW] Implement commands.run REST endpoint call

- core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
- core/src/main/kotlin/chat/rocket/core/internal/ReactionsAdapter.kt
- core/src/main/kotlin/chat/rocket/core/internal/model/ReactionPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
- core/src/main/kotlin/chat/rocket/core/model/Message.kt
- core/src/main/kotlin/chat/rocket/core/model/Reaction.kt
- core/src/main/kotlin/chat/rocket/core/model/Reactions.kt
- core/src/test/kotlin/chat/rocket/core/internal/ReactionsAdapterTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
> [NEW] Toggle reactions

- core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
> [NEW] Implement channels.join REST endpoint call

- common/build.gradle
- common/src/main/kotlin/chat/rocket/common/internal/FallbackSealedClass.kt
- common/src/main/kotlin/chat/rocket/common/model/SettingsOauth.kt
- compat/build.gradle
- core/build.gradle
- core/src/main/kotlin/chat/rocket/core/internal/model/ConfigurationsPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
- dependencies.gradle
- rxjava/build.gradle
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
> [NEW] List all oauth services

- core/src/main/kotlin/chat/rocket/core/internal/model/CasLoginPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/model/OauthLoginPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
Closes #5 
Closes #6 
Closes #7 
Closes #8 
Closes #88
> [NEW] Oauth login

- core/src/main/kotlin/chat/rocket/core/internal/model/Subscription.kt
- core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
> [New] Add favorite field in ChatRoom and Subscription object

- core/src/main/kotlin/chat/rocket/core/internal/model/CreateNewChannelPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Channel.kt
- core/src/main/kotlin/chat/rocket/core/model/CreateChannelResponse.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
Rest call to create new channel has been added. 
Fixes https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/issues/95
> [NEW] Rest call to create new channel

- common/src/main/kotlin/chat/rocket/common/RocketChatInvalidProtocolException.kt
- core/src/main/kotlin/chat/rocket/core/internal/SettingsAdapter.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
Disable ssl redirect on /api/info and throws an exception on redirects
> [NEW] Add support for HTTP servers

- common/src/main/kotlin/chat/rocket/common/model/SettingsOauth.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
Since we are supporting a flag to indicate that a service is wether custom, change our payload.
> [FIX] settings.oauth payload.

- core/src/main/kotlin/chat/rocket/core/internal/model/ForgotPasswordPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/model/SignUpPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
> [NEW] Add ForgotPassword.

- core/src/main/kotlin/chat/rocket/core/internal/realtime/ChatRoom.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/message/MethodCall.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
> [NEW] Add send typing status.

- core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/ChatRoom.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/message/MethodCall.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/message/Subscription.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Subscription.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/message/collection/StreamNotifyRoom.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
> [NEW] Subscribe typing status.

- core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
- core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
- core/src/main/kotlin/chat/rocket/core/model/Room.kt
> [NEW] Add broadcast property to Room and ChatRoom

- core/src/main/kotlin/chat/rocket/core/internal/SettingsAdapter.kt
Closes https://github.com/RocketChat/Rocket.Chat.Android/issues/1276
> [FIX] Fix null values on Settings Adapter

- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/GenericAttachment.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Closes https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/issues/163
> [NEW] Add chat room file list.

- core/src/main/kotlin/chat/rocket/core/model/Message.kt
> [NEW] Add unread property to Message object

- common/src/main/kotlin/chat/rocket/common/internal/FallbackSealedClassJsonAdapter.kt
- common/src/main/kotlin/chat/rocket/common/model/BaseRoom.kt
- common/src/main/kotlin/chat/rocket/common/model/BaseUser.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
- core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/RoomListAdapterTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/RolesTest.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Reverts RocketChat/Rocket.Chat.Kotlin.SDK#173
> Revert "[NEW] Changes necessary for DB integration on the App"

- dependencies.gradle
> [RELEASE] Merge beta into master/develop

- common/src/main/kotlin/chat/rocket/common/internal/FallbackSealedClassJsonAdapter.kt
- common/src/main/kotlin/chat/rocket/common/model/BaseRoom.kt
- common/src/main/kotlin/chat/rocket/common/model/BaseUser.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
- core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/RoomListAdapterTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/RolesTest.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Reverts RocketChat/Rocket.Chat.Kotlin.SDK#180
> [AGAIN][NEW] Changes necessary for DB integration on the App

- core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
> [NEW] Favorite/unfavorite chatroom

- core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Channel.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Commands.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Logout.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Message.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Permissions.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Push.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Spotlight.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
- core/src/test/kotlin/chat/rocket/core/internal/ReactionsAdapterTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/RoomListAdapterTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/CommandsTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/LogoutTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/PermissionsTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/RolesTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/SpotlightTest.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/UserTest.kt
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Adds the `user agent` when making the API requests.
> [NEW] User agent

- core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/AudioAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/FileAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/GenericFileAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/ImageAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/attachment/VideoAttachment.kt
- core/src/main/kotlin/chat/rocket/core/model/url/Meta.kt
In collaboration with pull [#1407](https://github.com/RocketChat/Rocket.Chat.Android/pull/1407) of Rocket.Chat.Android
> [FIX]  Added text and description fields for Image Attachment 

- core/src/main/java/chat/rocket/core/internal/RestMultiResult.java
- core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
- core/src/main/kotlin/chat/rocket/core/model/Removed.kt
- dependencies.gradle
- sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Needed for the spotlight+fixes on the app
> Update RestMultiResult to receive multiple types

- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
- core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/model/ReconnectionStrategy.kt
Fixes when manually reconnecting before the auto retry timer expires...
> [FIX] manual reconnection

- core/src/main/kotlin/chat/rocket/core/internal/model/MessageReportPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/Message.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
> [NEW] Implement call to REST endpoint chat.reportMessage

- core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
- core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
- core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
Part of https://github.com/RocketChat/Rocket.Chat.Android/issues/1230
> [NEW] Add invite and kick endpoints
